# InfiniteBuckets Spigot Plugin!
# Give players infinite buckets of water or lava
lava:
  display: "&cInfinite Lava Bucket"
  lore:
    - "&7&oTo infinity and beyond!"
    - "&7&oThis lava bucket can NEVER run out!"
    - " "
    - "&cInfinite Uses"

water:
  display: "&bInfinite Water Bucket"
  lore:
    - "&7&oTo infinity and beyond!"
    - "&7&oThis water bucket can NEVER run out!"
    - " "
    - "&cInfinite Uses"